# Generated by Django 3.2.13 on 2022-05-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('correct', models.IntegerField()),
                ('incorrect', models.IntegerField()),
                ('unknown', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srno', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=12)),
                ('purpose', models.CharField(max_length=50)),
                ('supervisor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=12)),
                ('snumber', models.CharField(max_length=12)),
                ('adharno', models.CharField(max_length=50)),
                ('cat', models.TextField(max_length=50)),
                ('blacklist', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('username', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('datein', models.DateField(null=True)),
                ('timein', models.TimeField(null=True)),
                ('dateout', models.DateField(null=True)),
                ('timeout', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=12)),
                ('adharno', models.CharField(max_length=12)),
                ('snumber', models.CharField(max_length=50)),
                ('cat', models.CharField(max_length=50)),
                ('blacklist', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('supervisor', models.TextField(null=True)),
                ('timein', models.TimeField(null=True)),
                ('datein', models.DateField(null=True)),
                ('timeout', models.TimeField(null=True)),
                ('dateout', models.DateField(null=True)),
            ],
        ),
    ]
