# Generated by Django 3.2.13 on 2022-05-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='super',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=12)),
                ('snumber', models.CharField(max_length=12)),
                ('adharno', models.CharField(max_length=50)),
                ('cat', models.TextField(max_length=50)),
                ('blacklist', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('username', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
            ],
        ),
    ]
