# Generated by Django 3.2.13 on 2022-05-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_super'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='supervisor',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
