# Generated by Django 3.2.13 on 2022-05-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220511_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='token',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
