# Generated by Django 3.2.13 on 2022-05-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_face_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='save',
            name='token',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='save',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
